apps:
  - icon: "fa fa-robot"
    title: "ai.sp-ps.ch"
    description: "Eine private KI. Verschiedene private Modelle und Modelle von OpenAI sind hier verfügbar."
    description-fr: "Une intelligence artificielle privée. Différents modèles privés ainsi que des modèles d'OpenAI sont disponibles ici."
    url: "https://ai.sp-ps.ch"

  - icon: "fa fa-language"
    title: "Antidote"
    description: "Eine Software zur sprachlichen Verfeinerung auf Französisch."
    description-fr: "Un logiciel de perfectionnement linguistique en français."
    url: "https://www.antidote.info/fr/"

  - icon: "fa fa-list-check"
    title: "Asana"
    description: "Unsere Aufgaben und Projekte"
    description-fr: "Nos missions et nos projets"
    url: "https://app.asana.com/-/login"

  - icon: "fa fa-language"
    title: "Deepl Pro"
    description: "Eine KI-Übersetzungsmaschine"
    description-fr: "Une machine de traduction basée sur l'intelligence artificielle"
    url: "https://deepl.com"

  - icon: "fa fa-circle"
    title: Holaspirit
    description: "Damit bilden wir unsere Organisation im Kreismodell gemäss Holokratie ab."
    description-fr: "Avec cela, nous représentons notre organisation selon le modèle en cercle de la holocratie."
    url: https://app.holaspirit.com/auth

  - icon: "fa fa-envelope"
    title: "maillings.sp-ps.ch"
    description: "Newsletter versenden"
    description-fr: "Envoyer des newsletters"
    url: "https://mailings.sp-ps.ch/"

  - icon: "fa fa-video"
    title: "Jitsi Meet"
    description: "Unsere Plattform für Online-Meetings."
    description-fr: "Notre plateforme pour les réunions en ligne."
    url: "https://meet.sp-ps.ch"

  - icon: "fa fa-images"
    title: Photoprism
    description: "Finde Bilder von Events und Personen der SP in unserer Bilderdatenbank."
    description-fr: "Trouvez des images d'événements et de personnes du PS dans notre base de données d'images."
    url: "https://photos.sp-ps.ch"

  - icon: "fa fa-database"
    title: Avanti
    description: "SP-Mobilisierungstool"
    description-fr: "Outil de mobilisation dula PS"
    url: "https://tel.sp-ps.ch"

  - icon: "fa fa-database"
    title: Tocco
    description: "Unsere Mitgliederverwaltunssoftware. Alle Infos beim Kreis Support und Personendatenmanagement."
    description-fr: "Notre logiciel de gestion des membres. Toutes les informations auprès du service du cercle et de la gestion des données personnelles."
    url: "http://login.sp-ps.ch/tocco"

  - icon: "fa fa-wand-magic-sparkles"
    title: Whisper
    description: "Du kannst damit Video und Audio transkribieren und sogar Musik von gesprochenem trennen lassen."
    description-fr: "Vous pouvez utiliser cela pour transcrire des vidéos et des audios, et même séparer la musique de la parole."
    url: "https://whisper.ai.sp-ps.ch/"

  - icon: "fa fa-headset"
    title: Support
    description: "Melde dich bei uns, wenn du ein Problem hast oder Hilfe brauchst."
    description-fr: "Contactez-nous si vous avez un problème ou besoin d'aide."
    url: "https://sp-ps.ch/support"

  - icon: "fa fa-inbox"
    title: Webmail
    description: "Webmail der SP Schweiz"
    description-fr: "Webmail du PS Suisse"
    url: "https://ch.exg7.exghost.com/owa/auth/logon.aspx"

  - icon: "fa fa-phone"
    title: "3CX"
    description: "Telefonanlage mit integrierter Datenbankabfrage"
    description-fr: "Poste téléphonique avec requête de base de données intégrée"
    url: "https://meucci.3cx.ch"

  - icon: "fa fa-comments"
    title: Mattermost
    description: "Interne Chatanwendung"
    description-fr: "Application de chat interne"
    url: "https://mattermost.sp-ps.ch"

  - icon: "fa fa-file-pdf"
    title: "PDF-Tool"
    description: "Werkzeug um PDFs zu verändern."
    description-fr: "Outil pour modifier des PDF"
    url: "https://pdf.sp-ps.ch"

  - icon: "fa fa-section"
    title: "Curia Vista"
    description: "Suche in der Geschäftsdatenbank des Schweizer Parlaments"
    description-fr: "Recherche dans la base de données des affaires du parlement suisse"
    url: "https://www.parlament.ch/de/search-affairs-advanced"

  - icon: "fa fa-book"
    title: "books.sp-sp.ch"
    description: "Interne Wissensdatenbank, user Bücherregal."
    description-fr: "Base de connaissances interne, notre bibliothèque."
    url: "https://books.sp-ps.ch"

  - icon: "fa fa-chart-line"
    title: "Matomo"
    description: "Webanalyse-Tool für unsere Webseiten."
    description-fr: "Outil d'analyse web pour nos sites internet."
    url: "https://matomo.spschweiz.ch"

  - icon: "fa fa-thermometer"
    title: "Status"
    description: "Überwacht unsere Dienste und benachrichtigt uns bei Ausfällen."
    description-fr: "Surveille nos services et nous avertit en cas de panne."
    url: "https://status.spschweiz.ch"